Initial Commit:
Not working similar problem as expr-trait-1 and expr-fsm-1.

```
$ cargo check
    Checking expr-traits-1 v0.1.0 (/home/wink/prgs/rust/myrepos/expr-fsm-0)
error[E0502]: cannot borrow `*self` as mutable because it is also borrowed as immutable
  --> src/main.rs:25:9
   |
25 |         self.current_state.process_msg(self, msg);
   |         ^^^^^^^^^^^^^^^^^^^-----------^^^^^^^^^^^
   |         |                  |
   |         |                  immutable borrow later used by call
   |         mutable borrow occurs here
   |         immutable borrow occurs here

For more information about this error, try `rustc --explain E0502`.
error: could not compile `expr-traits-1` due to previous error
```