wip: convert to pointers rather than indexes
Right now getting two errors:

 $ cargo build
    Compiling exper-fsm-0 v0.4.0 (/home/wink/prgs/rust/myrepos/exper-fsm-0)
  error[E0308]: mismatched types
   --> src/fn_ptr_state_machine.rs:67:26
    |
 67 |                 process: Self::state_process_add_or_mul,
    |                          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ one type is more general than the other
    |
    = note: expected fn pointer `for<'sm, 'a> fn(&'sm mut fn_ptr_state_machine::StateMachine<'sm>, &'a fn_ptr_state_machine::Protocol1) -> StateResult`
                 found fn item `fn(&mut fn_ptr_state_machine::StateMachine<'_>, &fn_ptr_state_machine::Protocol1) -> StateResult {fn_ptr_state_machine::StateMachine::<'_>::state_process_add_or_mul}`

 error[E0308]: mismatched types
   --> src/fn_ptr_state_machine.rs:74:26
    |
 74 |                 process: Self::state_process_any,
    |                          ^^^^^^^^^^^^^^^^^^^^^^^ one type is more general than the other
    |
    = note: expected fn pointer `for<'sm, 'a> fn(&'sm mut fn_ptr_state_machine::StateMachine<'sm>, &'a fn_ptr_state_machine::Protocol1) -> StateResult`
                 found fn item `fn(&mut fn_ptr_state_machine::StateMachine<'_>, &fn_ptr_state_machine::Protocol1) -> StateResult {fn_ptr_state_machine::StateMachine::<'_>::state_process_any}`

 For more information about this error, try `rustc --explain E0308`.
 error: could not compile `exper-fsm-0` due to 2 previous errors