wip: Doesn't work either
 $ cargo build
   Compiling exper-fsm-0 v0.4.0 (/home/wink/prgs/rust/myrepos/exper-fsm-0)
  error[E0515]: cannot return value referencing local data `sm.state_fns`
    --> src/fn_ptr_state_machine.rs:142:9
     |
 113 |         let initial_state_fns = &sm.state_fns[0];
     |                                  ------------ `sm.state_fns` is borrowed here
 ...
 142 |         sm
     |         ^^ returns a value referencing data owned by the current function

  error[E0505]: cannot move out of `sm` because it is borrowed
    --> src/fn_ptr_state_machine.rs:142:9
     |
 60  | impl<'a> StateMachine<'a> {
     |      -- lifetime `'a` defined here
 ...
 113 |         let initial_state_fns = &sm.state_fns[0];
     |                                  ------------ borrow of `sm.state_fns` occurs here
 ...
 142 |         sm
     |         ^^
     |         |
     |         move out of `sm` occurs here
     |         returning this value requires that `sm.state_fns` is borrowed for `'a`